### ISSUE TITLE
create a setup.py to install all the packages

### ISSUE THREAD

**Issue by pradal** [openalea-incubator/WheatFspm#2]
Add a setup.py that will install all the packages  once.
This setup.py will supplement each local setup.py

**Comment by pradal** [comment]
This is not possible using setuptools setup.py
However, I have deveoped in openalea.misc a multisetup strategy.
This will induce a dependecy on this package.

**Comment by rbarillot** [comment]
@pradal could you send me an example of the setup.py that I should have in the different submodule please?

**Comment by pradal** [comment]
I will make a PR on elong-wheat.

Le 27/03/2020 à 21:15, Romain Barillot a écrit :

**Comment by rbarillot** [comment]
@pradal could you make the PR on elongwheat such that I can see how the setup.py should look like pkease? TY

**Comment by pradal** [comment]
I have already added the setup.py in #3 
I close then this issue.
The other issue is reference here: https://github.com/openalea-incubator/elong-wheat/issues/1
